[project]
name = "flask-demo-full"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "openai>=1.63.2",
    "weave>=0.51.33",
]
